/**
 * Shared types for the resume pack (#241).
 */

/** One chunk reference in the build manifest. */
export interface ResumeChunkRef {
    chunkUrl: string;
    exportName: string;
}

/**
 * The `.vite/sigx-resume-manifest.json` shape emitted by `sigxResume()`
 * (`@sigx/vite/resume`): `components` maps `__resumeId` → upgrade chunk
 * (required for registry-less prod pages), `handlers` maps QRL symbols →
 * handler chunks (modulepreload hints only — resolution goes through the
 * client registry).
 */
export interface ResumeManifest {
    components: Record<string, ResumeChunkRef>;
    handlers: Record<string, ResumeChunkRef>;
}

export interface ResumePluginOptions {
    /**
     * Build manifest generated by `sigxResume()`. When provided, each
     * resumable component's boundary record carries its upgrade-chunk ref, so
     * the client can load it on demand without eager registration.
     *
     * @example
     * ```ts
     * import { resumeManifest } from 'virtual:sigx-manifests';
     * const app = defineApp(<App />).use(resumePlugin({ manifest: resumeManifest }));
     * ```
     */
    manifest?: ResumeManifest;

    /**
     * Client-side hydration mode for the app this plugin is installed on.
     *
     * - **`'auto'` (default)** — `hydrate()` walks the root as usual and
     *   intercepts resume boundaries on the way past, leaving them for the
     *   loader to wake on interaction. Everything *around* them hydrates.
     *   This is what an app-rooted `app.use(resumePlugin())` wants: an app
     *   with a root has a root to hydrate.
     * - **`'explicit'`** — no root walk at all; only table-listed boundaries
     *   are scheduled. Correct for an app-less resumable page, whose whole
     *   bootstrap is the generated loader entry — but note that such a page
     *   never calls `app.use()` in the first place.
     *
     * Until #483 this was **unconditionally `'explicit'`**, which made the
     * documented client recipe silently disable full-tree hydration: every
     * resume record is `hydrate: 'never'`, and explicit mode schedules only
     * table boundaries, so a coexisting app hydrated *nothing at all* and
     * shipped a dead shell. Resume gets its boundary isolation from the
     * server-set `hydrate: 'never'`, not from this default — unlike
     * `islandsPlugin`, where explicit mode IS the pack's semantics.
     */
    boundaries?: 'auto' | 'explicit';
}
