/**
 * Shared types for the resume pack (#241).
 */

/** One chunk reference in the build manifest. */
export interface ResumeChunkRef {
    chunkUrl: string;
    exportName: string;
}

/**
 * The `.vite/sigx-resume-manifest.json` shape emitted by `sigxResume()`
 * (`@sigx/vite/resume`): `components` maps `__resumeId` → upgrade chunk
 * (required for registry-less prod pages), `handlers` maps QRL symbols →
 * handler chunks (modulepreload hints only — resolution goes through the
 * client registry).
 */
export interface ResumeManifest {
    components: Record<string, ResumeChunkRef>;
    handlers: Record<string, ResumeChunkRef>;
}

export interface ResumePluginOptions {
    /**
     * Build manifest generated by `sigxResume()`. When provided, each
     * resumable component's boundary record carries its upgrade-chunk ref, so
     * the client can load it on demand without eager registration.
     *
     * @example
     * ```ts
     * import { resumeManifest } from 'virtual:sigx-manifests';
     * const app = defineApp(<App />).use(resumePlugin({ manifest: resumeManifest }));
     * ```
     */
    manifest?: ResumeManifest;
}
