/**
 * Islands SSR Plugin
 *
 * Implements the SSRPlugin interface to add islands architecture support:
 * - Selective hydration via client:* directives
 * - Signal state tracking and serialization for island components
 * - Client-side deferred hydration strategies (load, idle, visible, media, only)
 *
 * Async streaming is handled by the core server-renderer. This plugin augments
 * the streamed replacements with island-specific data (signal state, hydration info)
 * via the `onAsyncComponentResolved` hook.
 *
 * @example
 * ```ts
 * import { createSSR } from '@sigx/server-renderer';
 * import { islandsPlugin } from '@sigx/ssr-islands';
 *
 * const ssr = createSSR().use(islandsPlugin());
 * const html = await ssr.render(<App />);
 * ```
 */

import type { SSRPlugin, ResolvedBoundary } from '@sigx/server-renderer';
import type { SSRContext } from '@sigx/server-renderer';
import { serializeBoundaryProps, getTypeHandlers } from '@sigx/server-renderer/server';
import { registerClientPlugin, provideHydrateDefaults } from '@sigx/server-renderer/client';
import type { VNode, ComponentSetupContext, App } from 'sigx';
import type { signal } from 'sigx';
import {
    getHydrationDirective,
    filterClientDirectives,
} from './client-directives';

import { createTrackingSignal, serializeSignalState } from './server/render-component';

// One copy of the client hook logic: the app-rooted form registers the same
// hooks eagerly that hydrateIslands() registers lazily.
import { islandsClientHooks } from './client/plugin-hooks';

// ─── Plugin Data Types ──────────────────────────────────────────

interface IslandsPluginData {
    /** Per-component signal maps, keyed by component ID */
    signalMaps: Map<number, Map<string, any>>;
}

const PLUGIN_NAME = 'islands';

// ─── Plugin Options ─────────────────────────────────────────────

/** One island's chunk reference in the manifest. */
export interface IslandManifestEntry {
    chunkUrl: string;
    exportName: string;
}

/**
 * Manifest v2 — emitted by `sigxIslands()` from `@sigx/vite`. Adds
 * `runtimePreload`: the app chunk carrying the lazily-imported hydration
 * executor plus its transitive static imports (the sigx runtime), which the
 * plugin modulepreloads whenever a request records schedulable islands.
 */
export interface IslandsManifestV2 {
    version: 2;
    islands: Record<string, IslandManifestEntry>;
    runtimePreload?: string[];
}

export interface IslandsPluginOptions {
    /**
     * Island manifest mapping component names to their chunk URLs.
     * Generated by `sigxIslandsPlugin()` from `@sigx/vite` during build.
     *
     * When provided, each island's `chunkUrl` and `exportName` will be set
     * in the `__SIGX_BOUNDARIES__` table, enabling the client to load chunks
     * on-demand without requiring eager `registerComponent()` calls.
     *
     * Accepts both the v2 shape (`{ version: 2, islands, runtimePreload }`)
     * and the legacy flat name → entry map.
     *
     * @example
     * ```ts
     * import manifest from './dist/.vite/sigx-islands-manifest.json';
     * const ssr = createSSR().use(islandsPlugin({ manifest }));
     * ```
     */
    manifest?: IslandsManifestV2 | Record<string, IslandManifestEntry>;
}

/** Normalize the two accepted manifest shapes. */
function normalizeManifest(manifest: IslandsPluginOptions['manifest']): {
    islands: Record<string, IslandManifestEntry>;
    runtimePreload: string[];
} {
    if (!manifest) return { islands: {}, runtimePreload: [] };
    if ('islands' in manifest && typeof manifest.islands === 'object') {
        const v2 = manifest as IslandsManifestV2;
        return { islands: v2.islands ?? {}, runtimePreload: v2.runtimePreload ?? [] };
    }
    return { islands: manifest as Record<string, IslandManifestEntry>, runtimePreload: [] };
}

// ─── Plugin Implementation ──────────────────────────────────────

/**
 * Create an islands plugin — dual-shaped:
 *
 * - As an SSRPlugin (server: `createSSR().use(islandsPlugin())`): maps
 *   `client:*` directives onto boundary records via `resolveBoundary`,
 *   tracks signal state, and writes it into the core __SIGX_BOUNDARIES__
 *   table.
 * - As an app plugin (client: `app.use(islandsPlugin())`): declares islands
 *   mode by providing `{ boundaries: 'explicit' }` hydration defaults (only
 *   boundary-table entries hydrate — no root walk) and registers the
 *   signal-state restore hook. `app.hydrate('#app')` then does the rest.
 *
 * The standalone `hydrateIslands()` entry remains for app-less pages; pair
 * it with `registerClientPlugin(islandsPlugin())` for state restoration.
 */
export function islandsPlugin(options?: IslandsPluginOptions): SSRPlugin & { install(app: App): void } {
    const { islands: manifestIslands, runtimePreload } = normalizeManifest(options?.manifest);
    return {
        name: PLUGIN_NAME,

        install(app: App) {
            // Islands mode is an app declaration, carried by the plugin —
            // never implied by a package import (rfc-ssr-platform open
            // question 5, resolved as plugin-provided via the DI seam).
            provideHydrateDefaults(app._context, { boundaries: 'explicit' });
            registerClientPlugin(this as unknown as SSRPlugin);
        },

        server: {
            setup(ctx: SSRContext) {
                ctx.setPluginData<IslandsPluginData>(PLUGIN_NAME, {
                    signalMaps: new Map()
                });
            },

            resolveBoundary(vnode: VNode, ctx: SSRContext): ResolvedBoundary | undefined {
                const allProps = vnode.props || {};
                const hydration = getHydrationDirective(allProps);

                if (!hydration) return undefined; // Not an island — don't claim it

                const componentName = (vnode.type as any).__islandId || (vnode.type as any).__name || 'Anonymous';

                // Attach the chunk ref from the manifest if available
                let chunk: { url: string; export?: string } | undefined;
                if (componentName in manifestIslands) {
                    const entry = manifestIslands[componentName];
                    chunk = { url: entry.chunkUrl, export: entry.exportName };
                }

                // Strip client:* directives and framework-internal props, keeping
                // only the real props to serialize for client hydration. The key
                // is passed even when undefined — core must not fall back to its
                // own snapshot (it would re-include the directives).
                const { children: _children, slots: _slots, $models: _models, ...propsData } = filterClientDirectives(allProps);
                const props = serializeBoundaryProps(propsData, getTypeHandlers(ctx));

                // client:only decomposes into the two axes: skip the server
                // render, mount immediately on the client (rfc-ssr-platform §1).
                // Other directives set only the hydrate axis; flush is omitted —
                // islands never overrides the async-flush default.
                return hydration.strategy === 'only'
                    ? { flush: 'skip', hydrate: 'load', chunk, props }
                    : { hydrate: hydration.strategy, media: hydration.media, chunk, props };
            },

            transformComponentContext(
                ctx: SSRContext,
                vnode: VNode,
                componentCtx: ComponentSetupContext
            ): ComponentSetupContext | void {
                const hydration = getHydrationDirective(vnode.props || {});
                if (!hydration) return; // Not an island — don't touch

                // The boundary record exists before this hook runs (the
                // resolveBoundary consult precedes context construction). No
                // record means another plugin won the consult — leave it alone.
                // client:only never reaches here: its setup is suppressed.
                const id = ctx._componentStack[ctx._componentStack.length - 1];
                if (!ctx.getBoundary(id)) return;

                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME)!;

                // Set up signal tracking for state serialization
                const signalMap = new Map<string, any>();
                data.signalMaps.set(id, signalMap);

                // Swap signal function with tracking variant
                componentCtx.signal = createTrackingSignal(signalMap) as typeof signal;

                return componentCtx;
            },

            assets(ctx: SSRContext): { modulepreload?: string[] } | void {
                // Preload the lazily-imported hydration runtime whenever this
                // request recorded a schedulable island: the bytes download
                // off the critical path, execution still waits for the first
                // strategy to fire. `hydrate: 'never'` records are another
                // pack's to wake — never a reason to warm OUR runtime.
                if (runtimePreload.length === 0) return;
                for (const record of ctx._boundaries.values()) {
                    if (record.hydrate && record.hydrate !== 'never') {
                        return { modulepreload: runtimePreload };
                    }
                }
            },

            afterRenderComponent(
                id: number,
                _vnode: VNode,
                _html: string,
                ctx: SSRContext
            ): string | void {
                // Capture signal state into the core boundary record — the
                // table ships it to the client (#120). client:only never
                // reaches this hook (its render is skipped), so this only runs
                // for islands that actually rendered.
                const record = ctx.getBoundary(id);
                if (!record) return;

                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME);
                const signalMap = data?.signalMaps.get(id);
                if (signalMap && signalMap.size > 0) {
                    const state = serializeSignalState(signalMap);
                    if (state) {
                        record.state = state;
                    }
                }
            },

            onAsyncComponentResolved(
                id: number,
                _html: string,
                ctx: SSRContext
            ): { html?: string; preScript?: string } | void {
                // Re-capture signal state after async data loaded. Core re-emits
                // the mutated record as the __SIGX_BOUNDARIES__ preScript patch
                // (before $SIGX_REPLACE dispatches sigx:async-ready) — no
                // pack-owned patch script anymore.
                const record = ctx.getBoundary(id);
                if (!record) return;

                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME);
                const signalMap = data?.signalMaps.get(id);
                if (signalMap && signalMap.size > 0) {
                    const state = serializeSignalState(signalMap);
                    if (state) {
                        record.state = state;
                    }
                }
            }
        },

        // The hooks live in ./client/plugin-hooks so the standalone
        // hydrateIslands() entry can register them LAZILY (they ride the
        // hydration-core chunk); this app/SSR-rooted plugin object registers
        // the same hooks eagerly — full runtime by definition.
        client: islandsClientHooks.client
    };
}
