/**
 * Islands SSR Plugin
 *
 * Implements the SSRPlugin interface to add islands architecture support:
 * - Selective hydration via client:* directives
 * - Signal state tracking and serialization for island components
 * - Client-side deferred hydration strategies (load, idle, visible, media, only)
 *
 * Async streaming is handled by the core server-renderer. This plugin augments
 * the streamed replacements with island-specific data (signal state, hydration info)
 * via the `onAsyncComponentResolved` hook.
 *
 * @example
 * ```ts
 * import { createSSR } from '@sigx/server-renderer';
 * import { islandsPlugin } from '@sigx/ssr-islands';
 *
 * const ssr = createSSR().use(islandsPlugin());
 * const html = await ssr.render(<App />);
 * ```
 */

import type { SSRPlugin } from '@sigx/server-renderer';
import type { SSRContext } from '@sigx/server-renderer';
import type { VNode, ComponentSetupContext } from 'sigx';
import { signal } from 'sigx';
import {
    getHydrationDirective,
    filterClientDirectives,
    serializeProps,
} from './client-directives';

import { createTrackingSignal, serializeSignalState } from './server/render-component';
import {
    generateIslandDataScript,
    escapeJsonForScript
} from './server/render-islands';
import type { IslandInfo, HydrationStrategy } from './types';

import { scheduleComponentHydration } from './client/hydrate-islands';
import { hydrateLeftoverAsyncComponents } from './client/hydrate-async';

// ─── Plugin Data Types ──────────────────────────────────────────

interface IslandsPluginData {
    islands: Map<number, IslandInfo>;
    /** Per-component signal maps, keyed by component ID */
    signalMaps: Map<number, Map<string, any>>;
}

const PLUGIN_NAME = 'islands';

// ─── Plugin Options ─────────────────────────────────────────────

export interface IslandsPluginOptions {
    /**
     * Island manifest mapping component names to their chunk URLs.
     * Generated by `sigxIslandsPlugin()` from `@sigx/vite` during build.
     *
     * When provided, each island's `chunkUrl` and `exportName` will be set
     * in the `__SIGX_ISLANDS__` data, enabling the client to load chunks
     * on-demand without requiring eager `registerComponent()` calls.
     *
     * @example
     * ```ts
     * import manifest from './dist/island-manifest.json';
     * const ssr = createSSR().use(islandsPlugin({ manifest }));
     * ```
     */
    manifest?: Record<string, { chunkUrl: string; exportName: string }>;
}

// ─── Plugin Implementation ──────────────────────────────────────

/**
 * Create an islands SSR plugin.
 *
 * Server-side: intercepts components with `client:*` directives, tracks signal state,
 * manages async streaming, and injects `__SIGX_ISLANDS__` hydration data.
 *
 * Client-side: intercepts components with `client:*` during hydration walk,
 * schedules deferred hydration, and handles async component streaming.
 */
export function islandsPlugin(options?: IslandsPluginOptions): SSRPlugin {
    return {
        name: PLUGIN_NAME,

        server: {
            setup(ctx: SSRContext) {
                ctx.setPluginData<IslandsPluginData>(PLUGIN_NAME, {
                    islands: new Map(),
                    signalMaps: new Map()
                });
            },

            transformComponentContext(
                ctx: SSRContext,
                vnode: VNode,
                componentCtx: ComponentSetupContext
            ): ComponentSetupContext | void {
                const allProps = vnode.props || {};
                const hydration = getHydrationDirective(allProps);

                if (!hydration) return; // Not an island — don't touch

                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME)!;
                const componentName = (vnode.type as any).__islandId || (vnode.type as any).__name || 'Anonymous';

                // Get the component ID (already assigned by core renderer)
                const id = ctx._componentStack[ctx._componentStack.length - 1];

                // Strip client:* directives and framework-internal props, keeping
                // only the real props to serialize for client hydration.
                const { children: _children, slots: _slots, $models: _models, ...propsData } = filterClientDirectives(allProps);

                // Register this island
                const islandInfo: IslandInfo = {
                    strategy: hydration.strategy as HydrationStrategy,
                    media: hydration.media,
                    props: serializeProps(propsData),
                    componentId: componentName
                };

                // Attach chunk URL from manifest if available
                if (options?.manifest && componentName in options.manifest) {
                    const entry = options.manifest[componentName];
                    islandInfo.chunkUrl = entry.chunkUrl;
                    islandInfo.exportName = entry.exportName;
                }

                data.islands.set(id, islandInfo);

                // client:only is true skip-SSR: the component never renders on the
                // server (see `suppressComponentRender` below), so there is no state
                // to capture — don't bother swapping in a tracking signal. The
                // island is still registered above so it appears in __SIGX_ISLANDS__
                // (with no `state`), and the client mounts it fresh into the
                // placeholder.
                if (hydration.strategy === 'only') {
                    return componentCtx;
                }

                // Set up signal tracking for state serialization
                const signalMap = new Map<string, any>();
                data.signalMaps.set(id, signalMap);

                // Swap signal function with tracking variant
                componentCtx.signal = createTrackingSignal(signalMap) as typeof signal;

                return componentCtx;
            },

            suppressComponentRender(
                id: number,
                _vnode: VNode,
                ctx: SSRContext
            ): { placeholder?: string } | void {
                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME);
                if (!data) return;

                const islandInfo = data.islands.get(id);
                if (!islandInfo || islandInfo.strategy !== 'only') return;

                // client:only — true skip-SSR. Emit an empty placeholder instead of
                // rendering the component; the client clears it and mounts fresh.
                // `display:contents` keeps the wrapper layout-transparent.
                return { placeholder: `<div data-island="${id}" style="display:contents;"></div>` };
            },

            afterRenderComponent(
                id: number,
                vnode: VNode,
                html: string,
                ctx: SSRContext
            ): string | void {
                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME);
                if (!data) return;

                const islandInfo = data.islands.get(id);
                if (!islandInfo) return; // Not an island

                // Capture signal state. client:only never reaches this hook — its
                // render is suppressed (see suppressComponentRender) — so this only
                // runs for eager/deferred islands that actually rendered.
                const signalMap = data.signalMaps.get(id);
                if (signalMap && signalMap.size > 0) {
                    const state = serializeSignalState(signalMap);
                    if (state) {
                        islandInfo.state = state;
                    }
                }

                // Return html as-is (core already wraps with <!--$c:N-->)
                return;
            },

            handleAsyncSetup(
                id: number,
                ssrLoads: Promise<void>[],
                renderFn: () => any,
                ctx: SSRContext
            ): { mode: 'block' | 'stream' | 'skip'; placeholder?: string } | void {
                // Islands plugin no longer manages deferred renders.
                // Core handles async streaming; we just augment via onAsyncComponentResolved.
                // Return void to accept core's default (stream in streaming mode, block otherwise).
                return;
            },

            onAsyncComponentResolved(
                id: number,
                html: string,
                ctx: SSRContext
            ): { html?: string; preScript?: string } | void {
                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME);
                if (!data) return;

                const islandInfo = data.islands.get(id);
                if (!islandInfo) return; // Not an island — no augmentation needed

                // Capture final signal state after async data loaded
                const signalMap = data.signalMaps.get(id);
                if (signalMap && signalMap.size > 0) {
                    const state = serializeSignalState(signalMap);
                    if (state) {
                        islandInfo.state = state;
                    }
                }

                // Patch __SIGX_ISLANDS__ for this component as a preScript so the
                // updated data is in place BEFORE $SIGX_REPLACE dispatches
                // sigx:async-ready — otherwise the hydration listener (which
                // invalidates the cache and re-reads getIslandData) would observe
                // stale island info and miss the freshly captured state.
                const islandJson = escapeJsonForScript(JSON.stringify(islandInfo));
                const preScript = `
                    var ds=document.getElementById('__SIGX_ISLANDS__');
                    if(ds){try{var d=JSON.parse(ds.textContent||'{}');d[${id}]=${islandJson};ds.textContent=JSON.stringify(d);}catch(e){}}
                `;

                return { preScript };
            },

            getInjectedHTML(ctx: SSRContext): string {
                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME);
                if (!data || data.islands.size === 0) return '';

                const islandData: Record<number, IslandInfo> = {};
                data.islands.forEach((info, id) => {
                    islandData[id] = info;
                });

                return generateIslandDataScript(islandData);
            }
        },

        client: {
            hydrateComponent(
                vnode: VNode,
                dom: Node | null,
                parent: Node
            ): Node | null | undefined {
                const strategy = vnode.props ? getHydrationDirective(vnode.props) : null;

                if (!strategy) return undefined; // Not an island — let core handle it

                return scheduleComponentHydration(vnode, dom, parent, strategy);
            },

            afterHydrate(container: Element): void {
                hydrateLeftoverAsyncComponents(container);
            }
        }
    };
}
