/**
 * Islands SSR Plugin
 *
 * Implements the SSRPlugin interface to add islands architecture support:
 * - Selective hydration via client:* directives
 * - Signal state tracking and serialization for island components
 * - Client-side deferred hydration strategies (load, idle, visible, media, only)
 *
 * Async streaming is handled by the core server-renderer. This plugin augments
 * the streamed replacements with island-specific data (signal state, hydration info)
 * via the `onAsyncComponentResolved` hook.
 *
 * @example
 * ```ts
 * import { createSSR } from '@sigx/server-renderer';
 * import { islandsPlugin } from '@sigx/ssr-islands';
 *
 * const ssr = createSSR().use(islandsPlugin());
 * const html = await ssr.render(<App />);
 * ```
 */

import type { SSRPlugin, ResolvedBoundary } from '@sigx/server-renderer';
import type { SSRContext } from '@sigx/server-renderer';
import { serializeBoundaryProps, getTypeHandlers } from '@sigx/server-renderer/server';
import { registerClientPlugin, provideHydrateDefaults } from '@sigx/server-renderer/client';
import type { VNode, ComponentSetupContext, App } from 'sigx';
import { signal } from 'sigx';
import {
    getHydrationDirective,
    filterClientDirectives,
} from './client-directives';

import { createTrackingSignal, serializeSignalState } from './server/render-component';

import { consumePendingServerState, scheduleComponentHydration } from './client/hydrate-islands';
import { createRestoringSignal } from './client/restore-signal';

// ─── Plugin Data Types ──────────────────────────────────────────

interface IslandsPluginData {
    /** Per-component signal maps, keyed by component ID */
    signalMaps: Map<number, Map<string, any>>;
}

const PLUGIN_NAME = 'islands';

// ─── Plugin Options ─────────────────────────────────────────────

export interface IslandsPluginOptions {
    /**
     * Island manifest mapping component names to their chunk URLs.
     * Generated by `sigxIslandsPlugin()` from `@sigx/vite` during build.
     *
     * When provided, each island's `chunkUrl` and `exportName` will be set
     * in the `__SIGX_BOUNDARIES__` table, enabling the client to load chunks
     * on-demand without requiring eager `registerComponent()` calls.
     *
     * @example
     * ```ts
     * import manifest from './dist/island-manifest.json';
     * const ssr = createSSR().use(islandsPlugin({ manifest }));
     * ```
     */
    manifest?: Record<string, { chunkUrl: string; exportName: string }>;
}

// ─── Plugin Implementation ──────────────────────────────────────

/**
 * Create an islands plugin — dual-shaped:
 *
 * - As an SSRPlugin (server: `createSSR().use(islandsPlugin())`): maps
 *   `client:*` directives onto boundary records via `resolveBoundary`,
 *   tracks signal state, and writes it into the core __SIGX_BOUNDARIES__
 *   table.
 * - As an app plugin (client: `app.use(islandsPlugin())`): declares islands
 *   mode by providing `{ boundaries: 'explicit' }` hydration defaults (only
 *   boundary-table entries hydrate — no root walk) and registers the
 *   signal-state restore hook. `app.hydrate('#app')` then does the rest.
 *
 * The standalone `hydrateIslands()` entry remains for app-less pages; pair
 * it with `registerClientPlugin(islandsPlugin())` for state restoration.
 */
export function islandsPlugin(options?: IslandsPluginOptions): SSRPlugin & { install(app: App): void } {
    return {
        name: PLUGIN_NAME,

        install(app: App) {
            // Islands mode is an app declaration, carried by the plugin —
            // never implied by a package import (rfc-ssr-platform open
            // question 5, resolved as plugin-provided via the DI seam).
            provideHydrateDefaults((app as any)._context, { boundaries: 'explicit' });
            registerClientPlugin(this as unknown as SSRPlugin);
        },

        server: {
            setup(ctx: SSRContext) {
                ctx.setPluginData<IslandsPluginData>(PLUGIN_NAME, {
                    signalMaps: new Map()
                });
            },

            resolveBoundary(vnode: VNode, ctx: SSRContext): ResolvedBoundary | undefined {
                const allProps = vnode.props || {};
                const hydration = getHydrationDirective(allProps);

                if (!hydration) return undefined; // Not an island — don't claim it

                const componentName = (vnode.type as any).__islandId || (vnode.type as any).__name || 'Anonymous';

                // Attach the chunk ref from the manifest if available
                let chunk: { url: string; export?: string } | undefined;
                if (options?.manifest && componentName in options.manifest) {
                    const entry = options.manifest[componentName];
                    chunk = { url: entry.chunkUrl, export: entry.exportName };
                }

                // Strip client:* directives and framework-internal props, keeping
                // only the real props to serialize for client hydration. The key
                // is passed even when undefined — core must not fall back to its
                // own snapshot (it would re-include the directives).
                const { children: _children, slots: _slots, $models: _models, ...propsData } = filterClientDirectives(allProps);
                const props = serializeBoundaryProps(propsData, getTypeHandlers(ctx));

                // client:only decomposes into the two axes: skip the server
                // render, mount immediately on the client (rfc-ssr-platform §1).
                // Other directives set only the hydrate axis; flush is omitted —
                // islands never overrides the async-flush default.
                return hydration.strategy === 'only'
                    ? { flush: 'skip', hydrate: 'load', chunk, props }
                    : { hydrate: hydration.strategy, media: hydration.media, chunk, props };
            },

            transformComponentContext(
                ctx: SSRContext,
                vnode: VNode,
                componentCtx: ComponentSetupContext
            ): ComponentSetupContext | void {
                const hydration = getHydrationDirective(vnode.props || {});
                if (!hydration) return; // Not an island — don't touch

                // The boundary record exists before this hook runs (the
                // resolveBoundary consult precedes context construction). No
                // record means another plugin won the consult — leave it alone.
                // client:only never reaches here: its setup is suppressed.
                const id = ctx._componentStack[ctx._componentStack.length - 1];
                if (!ctx.getBoundary(id)) return;

                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME)!;

                // Set up signal tracking for state serialization
                const signalMap = new Map<string, any>();
                data.signalMaps.set(id, signalMap);

                // Swap signal function with tracking variant
                componentCtx.signal = createTrackingSignal(signalMap) as typeof signal;

                return componentCtx;
            },

            afterRenderComponent(
                id: number,
                _vnode: VNode,
                _html: string,
                ctx: SSRContext
            ): string | void {
                // Capture signal state into the core boundary record — the
                // table ships it to the client (#120). client:only never
                // reaches this hook (its render is skipped), so this only runs
                // for islands that actually rendered.
                const record = ctx.getBoundary(id);
                if (!record) return;

                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME);
                const signalMap = data?.signalMaps.get(id);
                if (signalMap && signalMap.size > 0) {
                    const state = serializeSignalState(signalMap);
                    if (state) {
                        record.state = state;
                    }
                }
            },

            onAsyncComponentResolved(
                id: number,
                _html: string,
                ctx: SSRContext
            ): { html?: string; preScript?: string } | void {
                // Re-capture signal state after async data loaded. Core re-emits
                // the mutated record as the __SIGX_BOUNDARIES__ preScript patch
                // (before $SIGX_REPLACE dispatches sigx:async-ready) — no
                // pack-owned patch script anymore.
                const record = ctx.getBoundary(id);
                if (!record) return;

                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME);
                const signalMap = data?.signalMaps.get(id);
                if (signalMap && signalMap.size > 0) {
                    const state = serializeSignalState(signalMap);
                    if (state) {
                        record.state = state;
                    }
                }
            }
        },

        client: {
            transformComponentContext(
                _vnode: VNode,
                componentCtx: ComponentSetupContext
            ): ComponentSetupContext | void {
                // Restore the server-captured signal state staged by the core
                // scheduler just before this island's hydrateComponent call.
                // Presence of pending state scopes this to islands —
                // non-island components have none and are left untouched
                // (mirrors the server hook guarding on the client:* directive).
                const state = consumePendingServerState();
                if (!state) return;

                componentCtx.signal = createRestoringSignal(state) as typeof signal;
                return componentCtx;
            },

            hydrateComponent(
                vnode: VNode,
                dom: Node | null,
                parent: Node
            ): Node | null | undefined {
                // Walk fallback for islands the boundary table did not record
                // (a stripped blob, or markup rendered without the table):
                // core's table interception claims recorded boundaries before
                // this hook runs, so this only fires for directive-carrying
                // components with no record.
                const strategy = vnode.props ? getHydrationDirective(vnode.props) : null;

                if (!strategy) return undefined; // Not an island — let core handle it

                return scheduleComponentHydration(vnode, dom, parent, strategy);
            }

            // No afterHydrate hook anymore: the core hydrator runs the
            // leftover streamed-boundary scan itself.
        }
    };
}
