/**
 * The scaffolded platform entry — written ONCE when absent, user-owned from
 * that moment (the adapter-package convention; PR #322). The shape is the
 * `export default { fetch }` object: on Vercel's Node runtime the launcher
 * detects a WEB handler by the presence of a `fetch` METHOD on the default
 * export (a bare default function would be treated as a legacy (req, res)
 * handler); the edge runtime gets a generated wrapper.
 */
export function scaffoldEntry(ssrEntryImport: string): string {
    return `// Vercel function entry — scaffolded by @sigx/vercel, YOURS from here on
// (rebuilds never touch it). The composition order is the app's routing
// policy and stays visible in this file:
//
//     static assets  ->  server functions  ->  document render
//
// Static assets never reach this code: config.json's filesystem handle
// serves them from static/ first (the fn route runs before it).
import { createFetchHandler } from '@sigx/server-renderer/server';
import { template, assets } from 'virtual:sigx-app';
import { createApp } from '${ssrEntryImport}';

const handler = createFetchHandler({
    template,
    app: (url) => createApp(url),
    document: { assets }
});

export default {
    async fetch(request: Request): Promise<Response> {
        // Using server functions (sigxServer() in vite.config)? Mount the
        // endpoint BEFORE the document render:
        //
        // import { handleServerFnRequest, matchesServerFn } from '@sigx/server/server';
        // import { serverFns } from 'virtual:sigx-server-fns';
        // if (matchesServerFn(request)) {
        //     return handleServerFnRequest(request, {
        //         resolve: (symbol) => serverFns[symbol]?.() ?? null
        //     });
        // }
        return handler(request);
    }
};
`;
}

/** The edge-runtime wrapper: edge entrypoints are bare default fetch fns. */
export function edgeWrapper(entryFile: string): string {
    return (
        `// Generated by @sigx/vercel (edge runtime): the edge entrypoint contract\n` +
        `// is a bare default fetch function; the user entry exports { fetch }.\n` +
        `import entry from './${entryFile}';\n` +
        `export default (request, event) => entry.fetch(request, event);\n`
    );
}
