#!/usr/bin/env node
/**
 * CLI to generate sigx component type definitions.
 * Run after `npm install` or manually to get intellisense without starting Vite.
 * 
 * Usage:
 *   npx sigx-types
 *   npx sigx-types --watch
 *   npx sigx-types --help
 */

import * as fs from 'fs';
import * as path from 'path';
import { pathToFileURL } from 'url';

// ============================================================================
// Component Scanner (shared with plugin)
// ============================================================================

interface ComponentInfo {
    tagName: string;
    exportName: string;
    filePath: string;
}

// Handles multi-line type parameters with [\s\S]*? (non-greedy any char including newlines)
const DEFINE_COMPONENT_REGEX = /(?:export\s+)?(?:const|let|var)\s+(\w+)\s*=\s*component\s*(?:<[\s\S]*?>)?\s*\(\s*["'`]([^"'`]+)["'`]/g;
const DEFAULT_EXPORT_REGEX = /export\s+default\s+component\s*(?:<[\s\S]*?>)?\s*\(\s*["'`]([^"'`]+)["'`]/g;

export function extractComponents(code: string, filePath: string): ComponentInfo[] {
    const components: ComponentInfo[] = [];
    DEFINE_COMPONENT_REGEX.lastIndex = 0;
    DEFAULT_EXPORT_REGEX.lastIndex = 0;

    let match;
    while ((match = DEFINE_COMPONENT_REGEX.exec(code)) !== null) {
        components.push({
            exportName: match[1],
            tagName: match[2],
            filePath
        });
    }

    while ((match = DEFAULT_EXPORT_REGEX.exec(code)) !== null) {
        const tagName = match[1];
        const exportName = tagName
            .split('-')
            .map(part => part.charAt(0).toUpperCase() + part.slice(1))
            .join('');
        components.push({
            exportName,
            tagName,
            filePath
        });
    }

    return components;
}

// ============================================================================
// Type Definition Generator
// ============================================================================

export function generateDts(components: ComponentInfo[], rootDir: string): string {
    if (components.length === 0) {
        return `// Auto-generated by @sigx/vite - no components found
export {};
`;
    }

    // Deduplicate by tagName
    const uniqueComponents = new Map<string, ComponentInfo>();
    for (const comp of components) {
        if (!uniqueComponents.has(comp.tagName)) {
            uniqueComponents.set(comp.tagName, comp);
        }
    }
    const dedupedComponents = Array.from(uniqueComponents.values());

    // Group by file
    const fileGroups = new Map<string, ComponentInfo[]>();
    for (const comp of dedupedComponents) {
        const existing = fileGroups.get(comp.filePath) || [];
        existing.push(comp);
        fileGroups.set(comp.filePath, existing);
    }

    // Generate imports
    const imports: string[] = [];
    for (const [filePath, comps] of fileGroups) {
        let relativePath = path.relative(rootDir, filePath).replace(/\\/g, '/');
        relativePath = relativePath.replace(/\.(tsx?|jsx?)$/, '');
        // Go up from node_modules/.sigx/ to project root (2 levels)
        relativePath = '../../' + relativePath;
        const exportNames = comps.map(c => c.exportName).join(', ');
        imports.push(`import type { ${exportNames} } from '${relativePath}';`);
    }

    // Generate registry entries
    const registryEntries = dedupedComponents
        .map(c => `        '${c.tagName}': typeof ${c.exportName};`)
        .join('\n');

    return `// Auto-generated by @sigx/vite - DO NOT EDIT
// This file provides type definitions for custom elements defined with component
// Regenerate with: npx sigx-types

${imports.join('\n')}

declare module '@sigx/runtime-core' {
    interface CustomElementRegistry {
${registryEntries}
    }
}

export {};
`;
}

/**
 * Generate a components.ts file with global declarations like ui.button.primary
 */
export function generateComponentsTs(components: ComponentInfo[], rootDir: string): string {
    if (components.length === 0) {
        return `// Auto-generated by @sigx/vite - no components found
export {};
`;
    }

    // Deduplicate by tagName
    const uniqueComponents = new Map<string, ComponentInfo>();
    for (const comp of components) {
        if (!uniqueComponents.has(comp.tagName)) {
            uniqueComponents.set(comp.tagName, comp);
        }
    }
    const dedupedComponents = Array.from(uniqueComponents.values());

    // Build nested structure: "ui-button-primary" -> ui.button.primary
    interface NestedNode {
        comp?: ComponentInfo;
        children: Map<string, NestedNode>;
    }

    const rootNodes = new Map<string, NestedNode>();

    for (const comp of dedupedComponents) {
        const parts = comp.tagName.split('-');
        if (parts.length >= 2) {
            const prefix = parts[0];
            const pathParts = parts.slice(1);

            if (!rootNodes.has(prefix)) {
                rootNodes.set(prefix, { children: new Map() });
            }

            let current = rootNodes.get(prefix)!;
            for (let i = 0; i < pathParts.length; i++) {
                const part = pathParts[i];
                if (!current.children.has(part)) {
                    current.children.set(part, { children: new Map() });
                }
                current = current.children.get(part)!;

                if (i === pathParts.length - 1) {
                    current.comp = comp;
                }
            }
        }
    }

    // Generate imports (group by file)
    const fileGroups = new Map<string, ComponentInfo[]>();
    for (const comp of dedupedComponents) {
        const existing = fileGroups.get(comp.filePath) || [];
        existing.push(comp);
        fileGroups.set(comp.filePath, existing);
    }

    const imports: string[] = [];
    for (const [filePath, comps] of fileGroups) {
        let relativePath = path.relative(rootDir, filePath).replace(/\\/g, '/');
        relativePath = relativePath.replace(/\.(tsx?|jsx?)$/, '');
        relativePath = '../../' + relativePath;

        const exportNames = comps.map(c => c.exportName).join(', ');
        imports.push(`import { ${exportNames} } from '${relativePath}';`);
    }

    // Helper to generate nested object literal
    function generateNestedObject(node: NestedNode, indent: string): string {
        if (node.comp && node.children.size > 0) {
            const childProps = Array.from(node.children.entries())
                .map(([key, child]) => {
                    if (child.comp && child.children.size === 0) {
                        return `${key}: ${child.comp.exportName}`;
                    } else {
                        return `${key}: ${generateNestedObject(child, indent + '    ')}`;
                    }
                })
                .join(', ');
            return `Object.assign(${node.comp.exportName}, { ${childProps} })`;
        } else if (node.comp) {
            return node.comp.exportName;
        } else {
            const props = Array.from(node.children.entries())
                .map(([key, child]) => {
                    const value = generateNestedObject(child, indent + '    ');
                    return `${indent}    ${key}: ${value}`;
                })
                .join(',\n');
            return `{\n${props}\n${indent}}`;
        }
    }

    // Helper to generate nested type declaration
    function generateNestedType(node: NestedNode, indent: string): string {
        if (node.comp && node.children.size > 0) {
            const childTypes = Array.from(node.children.entries())
                .map(([key, child]) => {
                    const childType = generateNestedType(child, indent + '    ');
                    return `readonly ${key}: ${childType}`;
                })
                .join('; ');
            return `typeof ${node.comp.exportName} & { ${childTypes} }`;
        } else if (node.comp) {
            return `typeof ${node.comp.exportName}`;
        } else {
            const props = Array.from(node.children.entries())
                .map(([key, child]) => {
                    const childType = generateNestedType(child, indent + '    ');
                    return `${indent}    readonly ${key}: ${childType}`;
                })
                .join(';\n');
            return `{\n${props}\n${indent}}`;
        }
    }

    const objectDeclarations: string[] = [];
    const globalDeclarations: string[] = [];
    const prefixes: string[] = [];

    for (const [prefix, node] of rootNodes) {
        prefixes.push(prefix);
        const objValue = generateNestedObject(node, '');
        objectDeclarations.push(`const _${prefix} = ${objValue} as const;`);

        const typeValue = generateNestedType(node, '    ');
        globalDeclarations.push(`    const ${prefix}: ${typeValue};`);
    }

    return `// Auto-generated by @sigx/vite - DO NOT EDIT
// This file provides global component objects for intellisense without imports
// Usage: <ui.button variant="primary" /> or <ui.button.primary />

${imports.join('\n')}

// Create the actual runtime objects
${objectDeclarations.join('\n\n')}

// Declare globals
declare global {
${globalDeclarations.join('\n')}
}

// Assign to globalThis for runtime
${prefixes.map(prefix => `(globalThis as any).${prefix} = _${prefix};`).join('\n')}

export { ${prefixes.map(p => `_${p} as ${p}`).join(', ')} };
`;
}

// ============================================================================
// File Scanner
// ============================================================================

interface ScanOptions {
    include: string[];
    exclude: string[];
}

export function matchGlob(filePath: string, pattern: string): boolean {
    const regexPattern = pattern
        .replace(/\./g, '\\.')
        .replace(/\*\*/g, '<<<GLOBSTAR>>>')
        .replace(/\*/g, '[^/]*')
        .replace(/<<<GLOBSTAR>>>/g, '.*');
    const regex = new RegExp(`(^|/)${regexPattern}$`);
    return regex.test(filePath);
}

export function shouldProcess(filePath: string, options: ScanOptions): boolean {
    const normalizedPath = filePath.replace(/\\/g, '/');

    for (const pattern of options.exclude) {
        if (matchGlob(normalizedPath, pattern)) {
            return false;
        }
    }

    for (const pattern of options.include) {
        if (matchGlob(normalizedPath, pattern)) {
            return true;
        }
    }

    return false;
}

export function scanDirectory(dir: string, options: ScanOptions, components: ComponentInfo[]): void {
    if (!fs.existsSync(dir)) return;

    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);

        if (entry.isDirectory()) {
            if (entry.name === 'node_modules' || entry.name.startsWith('.')) {
                continue;
            }
            scanDirectory(fullPath, options, components);
        } else if (entry.isFile() && /\.(tsx?|jsx?)$/.test(entry.name)) {
            if (shouldProcess(fullPath, options)) {
                try {
                    const code = fs.readFileSync(fullPath, 'utf-8');
                    const fileComponents = extractComponents(code, fullPath);
                    components.push(...fileComponents);
                } catch {
                    // Ignore read errors
                }
            }
        }
    }
}

// ============================================================================
// CLI
// ============================================================================

function printHelp() {
    console.log(`
sigx-types - Generate TypeScript definitions for sigx custom elements

Usage:
  npx sigx-types [options]

Options:
  --help, -h      Show this help message
  --watch, -w     Watch for file changes and regenerate
  --out, -o       Output directory (default: node_modules/.sigx)
  --include       Glob patterns to include (comma-separated)
  --exclude       Glob patterns to exclude (comma-separated)

Examples:
  npx sigx-types
  npx sigx-types --watch
  npx sigx-types --out .sigx-types
  npx sigx-types --include "src/**/*.tsx,components/**/*.tsx"
`);
}

function main() {
    const args = process.argv.slice(2);

    if (args.includes('--help') || args.includes('-h')) {
        printHelp();
        process.exit(0);
    }

    const watch = args.includes('--watch') || args.includes('-w');

    // Parse --out
    let outDir = 'node_modules/.sigx';
    const outIndex = args.findIndex(a => a === '--out' || a === '-o');
    if (outIndex !== -1 && args[outIndex + 1]) {
        outDir = args[outIndex + 1];
    }

    // Parse --include
    let include = ['**/*.tsx', '**/*.ts', '**/*.jsx'];
    const includeIndex = args.findIndex(a => a === '--include');
    if (includeIndex !== -1 && args[includeIndex + 1]) {
        include = args[includeIndex + 1].split(',').map(s => s.trim());
    }

    // Parse --exclude
    let exclude = ['node_modules/**', 'dist/**', '**/*.d.ts'];
    const excludeIndex = args.findIndex(a => a === '--exclude');
    if (excludeIndex !== -1 && args[excludeIndex + 1]) {
        exclude = args[excludeIndex + 1].split(',').map(s => s.trim());
    }

    const rootDir = process.cwd();
    const options: ScanOptions = { include, exclude };

    function generate() {
        const components: ComponentInfo[] = [];
        scanDirectory(rootDir, options, components);

        const dtsDir = path.resolve(rootDir, outDir);
        if (!fs.existsSync(dtsDir)) {
            fs.mkdirSync(dtsDir, { recursive: true });
        }

        // Write components.d.ts (type augmentation)
        const dtsContent = generateDts(components, rootDir);
        const dtsPath = path.join(dtsDir, 'components.d.ts');
        fs.writeFileSync(dtsPath, dtsContent, 'utf-8');

        // Write components.ts (grouped exports like ui.button)
        const tsContent = generateComponentsTs(components, rootDir);
        const tsPath = path.join(dtsDir, 'components.ts');
        fs.writeFileSync(tsPath, tsContent, 'utf-8');

        console.log(`[sigx] Generated types for ${components.length} components → ${outDir}/`);
    }

    // Initial generation
    generate();

    if (watch) {
        console.log('[sigx] Watching for changes...');

        // Simple polling watcher (cross-platform)
        const watchDirs = ['src', 'components', 'pages'].filter(d => fs.existsSync(path.join(rootDir, d)));

        if (watchDirs.length === 0) {
            console.log('[sigx] No src/components/pages directories found to watch');
            return;
        }

        for (const dir of watchDirs) {
            fs.watch(path.join(rootDir, dir), { recursive: true }, (eventType, filename) => {
                if (filename && /\.(tsx?|jsx?)$/.test(filename)) {
                    console.log(`[sigx] Change detected: ${filename}`);
                    generate();
                }
            });
        }

        // Keep process alive
        process.stdin.resume();
        console.log('[sigx] Press Ctrl+C to stop');
    }
}

// Only auto-execute when this module is the CLI entry point (i.e. running via
// `node cli.js` or the `sigx-types` bin). When imported by tests or another
// module, `main()` is left for the caller to invoke.
const _entry = process.argv[1];
if (_entry && import.meta.url === pathToFileURL(_entry).href) {
    main();
}

// Exposed for tests / advanced consumers; not part of the stable public API.
export { main as _main };
