/**
 * Client-side QRL registry (#241).
 *
 * `virtual:sigx-resume` (generated by `sigxResume()`) registers one lazy
 * loader per handler symbol —
 * `__registerResumeQrl(sym, () => import(...).then(m => m[sym]))`
 * (the loader resolves to the handler FUNCTION, not the module namespace).
 * The dynamic import is the code-split point: it executes only when
 * delegation resolves the symbol on first interaction. Resolution is
 * registry-only in dev AND prod (symbols are content-hashed and build-stable;
 * the manifest is preload hints, never the resolution path).
 */

/** Resolves to the handler function its symbol names. */
export type QrlLoader = () => Promise<(...args: any[]) => unknown>;

const loaders = new Map<string, QrlLoader>();
const resolved = new Map<string, (...args: unknown[]) => unknown>();

/** Register a lazy loader for a QRL symbol (first registration wins). */
export function __registerResumeQrl(symbol: string, loader: QrlLoader): void {
    if (!loaders.has(symbol)) loaders.set(symbol, loader);
}

/** Resolve a QRL symbol to its handler function, importing on first use. */
export async function resolveQrl(symbol: string): Promise<((...args: unknown[]) => unknown) | null> {
    const cached = resolved.get(symbol);
    if (cached) return cached;

    const loader = loaders.get(symbol);
    if (!loader) {
        if (__DEV__) {
            console.warn(
                `[sigx resume] No QRL registered for "${symbol}" — is 'virtual:sigx-resume' ` +
                `imported (the generated entry does this), and does the build match the ` +
                `server-rendered HTML?`
            );
        }
        return null;
    }

    const handler = await loader();
    if (typeof handler !== 'function') {
        if (__DEV__) {
            console.warn(
                `[sigx resume] QRL "${symbol}" resolved to ${typeof handler} — expected the ` +
                `handler function exported from its handlers module.`
            );
        }
        return null;
    }
    resolved.set(symbol, handler as (...args: unknown[]) => unknown);
    return resolved.get(symbol)!;
}

/** Drop all registrations and cached handlers — SPA navigation and tests. */
export function resetResumeQrls(): void {
    loaders.clear();
    resolved.clear();
}
