/**
 * Client-side QRL registry (#241).
 *
 * `virtual:sigx-resume` (generated by `sigxResume()`) registers one lazy
 * loader per handler symbol —
 * `__registerResumeQrl(sym, () => import(...).then(m => m[sym]))`
 * (the loader resolves to the handler FUNCTION, not the module namespace).
 * The dynamic import is the code-split point: it executes only when
 * delegation resolves the symbol on first interaction. Resolution is
 * registry-only in dev AND prod (symbols are content-hashed and build-stable;
 * the manifest is preload hints, never the resolution path).
 */

/** Resolves to the handler function its symbol names. */
export type QrlLoader = () => Promise<(...args: any[]) => unknown>;

const loaders = new Map<string, QrlLoader>();
// In-flight promises double as the settled cache — concurrent resolveQrl
// calls for one symbol must share a single loader() invocation.
const resolutions = new Map<string, Promise<((...args: unknown[]) => unknown) | null>>();

/** Register a lazy loader for a QRL symbol (first registration wins). */
export function __registerResumeQrl(symbol: string, loader: QrlLoader): void {
    if (!loaders.has(symbol)) loaders.set(symbol, loader);
}

/** Resolve a QRL symbol to its handler function, importing on first use. */
export function resolveQrl(symbol: string): Promise<((...args: unknown[]) => unknown) | null> {
    let resolution = resolutions.get(symbol);
    if (resolution) return resolution;

    const loader = loaders.get(symbol);
    if (!loader) {
        if (__DEV__) {
            console.warn(
                `[sigx resume] No QRL registered for "${symbol}" — is 'virtual:sigx-resume' ` +
                `imported (the generated entry does this), and does the build match the ` +
                `server-rendered HTML?`
            );
        }
        // Not cached: a late-registering registry can still succeed later.
        return Promise.resolve(null);
    }

    // Promise.resolve().then defers a synchronously-throwing loader into a
    // rejection instead of throwing through resolveQrl itself.
    resolution = Promise.resolve().then(loader).then(
        (handler) => {
            if (typeof handler !== 'function') {
                if (__DEV__) {
                    console.warn(
                        `[sigx resume] QRL "${symbol}" resolved to ${typeof handler} — expected the ` +
                        `handler function exported from its handlers module.`
                    );
                }
                return null;
            }
            return handler as (...args: unknown[]) => unknown;
        },
        (error) => {
            // Failed imports retry on the next interaction.
            resolutions.delete(symbol);
            throw error;
        }
    );
    resolutions.set(symbol, resolution);
    return resolution;
}

/** Drop all registrations and cached/in-flight handlers — SPA nav and tests. */
export function resetResumeQrls(): void {
    loaders.clear();
    resolutions.clear();
}
