/**
 * The scaffolded platform entry — written ONCE when absent, user-owned from
 * that moment (the adapter-package convention; PR #322). The entry keeps
 * the `export default { fetch }` shape shared by every sigx platform entry;
 * the Netlify-specific function contract (bare default fn + in-source
 * `config`) lives in the GENERATED wrapper, not in user code.
 *
 * The commented server-fn mount carries `renderBoundaries` too (#564): that
 * option is OPTIONAL, so an entry that omits it type-checks and silently
 * loses single-flight boundary refresh. The committed example entries are the
 * full reference (`examples/resume/src/entry.netlify.ts`, rfc-deploy §4.1).
 */
export function scaffoldEntry(ssrEntryImport: string): string {
    return `// Netlify function entry — scaffolded by @sigx/netlify, YOURS from here on
// (rebuilds never touch it). The composition order is the app's routing
// policy and stays visible in this file:
//
//     static assets  ->  server functions  ->  document render
//
// Static assets never reach this code: the generated function config sets
// preferStatic, so CDN files win before the catch-all runs.
import { createFetchHandler } from '@sigx/server-renderer/server';
import { template, assets } from 'virtual:sigx-app';
import { createApp } from '${ssrEntryImport}';

const handler = createFetchHandler({
    template,
    app: (url) => createApp(url),
    document: { assets }
});

export default {
    async fetch(request: Request): Promise<Response> {
        // Using server functions (sigxServer() in vite.config)? Mount the
        // endpoint BEFORE the document render:
        //
        // import { handleServerFnRequest, matchesServerFn } from '@sigx/server/server';
        // import { serverFns } from 'virtual:sigx-server-fns';
        // if (matchesServerFn(request)) {
        //     return handleServerFnRequest(request, {
        //         resolve: (symbol) => serverFns[symbol]?.() ?? null,
        //         // Using @sigx/resume? Single-flight boundary refresh
        //         // (rfc-server §6.3) needs this option; without it a
        //         // mutation's response carries no fresh HTML and the
        //         // client pays a second round trip to converge:
        //         // renderBoundaries: createBoundaryRefresh({
        //         //     plugins: [resumePlugin({ manifest: resumeManifest })],
        //         //     components: { /* __resumeId -> server component */ }
        //         // })
        //     });
        // }
        return handler(request);
    }
};
`;
}

/**
 * The generated function file (Netlify Functions v2): a bare default fetch
 * fn bridging the entry's `{ fetch }` shape, plus the in-source config —
 * URLPattern catch-all, static files winning (`preferStatic`), and
 * `nodeBundler: 'none'` because the output is final (fully prebundled).
 */
export function functionWrapper(entryFile: string, version: string): string {
    return `// Generated by @sigx/netlify — the Functions v2 contract over the user's
// { fetch } entry. Self-contained: the bundled entry sits beside this file.
import entry from './${entryFile}';

export default (request, context) => entry.fetch(request, context);

export const config = {
    path: '/*',
    preferStatic: true,
    name: 'sigx SSR',
    generator: '@sigx/netlify@${version}',
    nodeBundler: 'none',
    includedFiles: ['**/*']
};
`;
}
